//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFakeProductIdentificationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string pr_id { get; set; }
        public string pr_name { get; set; }
        public string pr_branch { get; set; }
        public string pr_type { get; set; }
        public string pr_origin { get; set; }
        public Nullable<double> pr_price { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
